name: dot_test
description: A Flutter application for controlling Bluetooth devices with an 8x8 dot matrix.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.33.4
  permission_handler: ^10.3.0
  provider: ^6.0.0
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
